use_frameworks!

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'ShareTripSDK_Example' do
  pod 'ShareTripSDK', :path => '../'
  
  target 'ShareTripSDK_Tests' do
    inherit! :search_paths
    
    
  end
end
