# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'STDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'JWT'
  pod 'PKHUD'
  pod 'Base64'
  pod 'Koloda'
  pod 'BlueECC'
  pod 'BlueRSA'
  pod 'Alamofire'
  pod 'lottie-ios'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'Bolts-Swift'
  pod 'BlueCryptor'
  pod 'FloatingPanel'
  pod 'GoogleSignIn'
  pod 'ImageSlideshow'
  pod 'JTAppleCalendar'
  pod 'SwiftKeychainWrapper'
  pod 'Socket.IO-Client-Swift'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseAnalytics'
  pod 'FirebaseMessaging'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseRemoteConfig'
  pod 'FirebaseDynamicLinks'
  pod 'IQKeyboardManagerSwift'
  pod 'FirebaseCoreDiagnostics'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
